language: python
python:
- "3.3"
services:
- postgresql
addons:
  postgresql: "9.2"
env:
- DJANGO=1.8.4 DB=postgres
install:
- python setup.py -q install
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- python wsgi/djYlplines/manage.py test
notifications:
  email:
    recipients:
      - jeffcjlee@gmail.com
    on_success: never
    on_failure: never